# Generated by Django 5.2.4 on 2025-08-16 09:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_message_airesponse_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoints',
            fields=[
                ('thread_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('checkpoint_id', models.CharField(max_length=255)),
                ('parent_checkpoint_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=50)),
                ('checkpoint', models.TextField()),
                ('metadata', models.TextField()),
            ],
            options={
                'verbose_name': 'Checkpoint',
                'verbose_name_plural': 'Checkpoints',
                'db_table': 'checkpoints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thread_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('conversation_title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation Record',
                'verbose_name_plural': 'Conversation Records',
                'db_table': 'conversation_record',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyMaterialFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Study Material File',
                'verbose_name_plural': 'Study Material Files',
                'db_table': 'study_material_files',
            },
        ),
        migrations.CreateModel(
            name='StudyMaterials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_plan', models.TextField()),
            ],
            options={
                'verbose_name': 'Study Material',
                'verbose_name_plural': 'Study Materials',
                'db_table': 'study_materials',
            },
        ),
        migrations.RemoveField(
            model_name='airesponse',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
