# Generated by Django 5.2.4 on 2025-08-16 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_checkpoints_conversationrecord_studymaterialfiles_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studymaterialfiles',
            name='study_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chat.studymaterials'),
        ),
        migrations.AddField(
            model_name='conversationrecord',
            name='study_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='chat.studymaterials'),
        ),
        migrations.DeleteModel(
            name='AIResponse',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
